# Generated by Django 3.1.2 on 2021-04-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='price',
            field=models.IntegerField(null=True, verbose_name='金額'),
        ),
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.TextField(null=True, verbose_name='タイトル'),
        ),
    ]
